#!/usr/bin/env python
import sys
import subprocess
import os

COMMANDS = ['test','track','hardware','simtrack','showgps', 'simnav','clean']
DEFAULT_COMMAND = 'test'

from src import wiring
from test import sim_wiring

def wiring():
    return wiring.Wiring()

sim_wiring = sim_wiring.SimWiring()

if __name__ == '__main__':
    command =  sys.argv[1] if len(sys.argv) > 1 else DEFAULT_COMMAND

    if len(sys.argv) > 2 or command not in COMMANDS:
        sys.exit('Usage: %s [%s]' % (sys.argv[0],'|'.join(COMMANDS)))

    if command == 'test':
        subprocess.call([sys.executable, '-m', 'unittest', 'discover', '-s','test'])

    if command == 'hardware':
        subprocess.call([sys.executable, '-m', 'unittest', 'discover', '-s','hw_integration_test'])

    if command == 'track':
        wiring().tracker.track(30)

    if command == 'showgps':
        wiring().showgps()
        
    if command == 'simtrack':
        sim_wiring.tracker_simulator().track(3)
        
    if command == 'simnav':
        sim_wiring.follower_simulator().follow_route(sim_wiring.manchester_tour())
        
    if command == 'nav':
        wiring().follower.follow_route(sim_wiring.manchester_tour())

    if command == 'clean':
        for path,dirs,filenames in os.walk('.'):
            for filename in filenames:
                if filename.endswith('.pyc'):
                    file_to_delete = os.path.normpath(path + '/' + filename)
                    os.remove(file_to_delete)
        print 'removed all .pyc files'
