#!/usr/bin/env python
import sys
import subprocess
import logging
from logging.handlers import TimedRotatingFileHandler

from src import *

COMMANDS = ['test','track','integration','simulate']
DEFAULT_COMMAND = 'test'
LOGGING_FORMAT = '%(asctime)s,%(levelname)s,%(message)s'

def application_logger(appname):
    logHandler = TimedRotatingFileHandler("/var/log/pi-nav/" + appname,when="midnight",backupCount=30)
    logHandler.setFormatter(logging.Formatter(LOGGING_FORMAT))
    logger = logging.getLogger(appname)
    logger.addHandler( logHandler )
    logger.setLevel( logging.INFO )
    return logger

if __name__ == '__main__':
    command =  sys.argv[1] if len(sys.argv) > 1 else DEFAULT_COMMAND

    if len(sys.argv) > 2 or command not in COMMANDS:
        sys.exit('Usage: %s [%s]' % (sys.argv[0],'|'.join(COMMANDS)))

    if command == 'test':
        subprocess.call([sys.executable, '-m', 'unittest', 'discover', '-s','test'])

    if command == 'integration':
        subprocess.call([sys.executable, '-m', 'unittest', 'discover', '-s','integration_test'])

    if command == 'track':
        gps = gps_reader.GpsReader()
        gps.start()
        main.App(application_logger("track"),gps,timed_callback.TimedCallback()).track(30)

    if command == 'simulate':
        gps = fake_gps.FakeGPS()
        logging.basicConfig(format=LOGGING_FORMAT, level=logging.DEBUG)
        logger = logging.getLogger("simulate")
        main.App(logger,gps,timed_callback.TimedCallback()).track(3)
